### ISSUE TITLE
Server completely un-joinable after restart, corrupted .explored files?

### ISSUE THREAD

**Issue by brahaney** [Mydayyy/Valheim-ServerSideMap#18]
First off-- love the mod concept. Until a restart it works great! My friends and I were loving the sharing. If theres any way I can help to further debug this or anything please let me know. I'm a Software Engineer in Test so, testing/debugging is my jam. Is there a way to activate like a debug mode for BepInEx or just this mod, to get some logging from the events I describe below? Currently nothing at all happens in the logs.

## The issue
This issue is consistently replicable in my environment. I have not yet tried isolating just this mod to replicate but if I have time to do so I will post my findings.

My server is scheduled to do check for updates nightly, which currently results in a restart. Each morning this results in being completely unable to reconnect to the server. There are no errors in the server log or client log-- when connecting, instead of prompting for my password, I get the following two screens:

![image](https://user-images.githubusercontent.com/4593316/110243499-a9419900-7f28-11eb-8ff1-4b7adab55e37.png)
![image](https://user-images.githubusercontent.com/4593316/110243508-b2cb0100-7f28-11eb-9a6f-d6dec51257dc.png)

The connection issue applies to all users, not only users with the mod installed. One of our players is still running completely vanilla client and cannot connect either once this issue begins.

I've deduced this to be an issue with SSM. It's the only mod I had added since the crashes started, and I can resolve the issue without removing the mod from the server or by simply deleting or moving `Wootheim2.mod.serversidemap.explored` and restarting.

This issue has replicated each time my server has restarted to check for updates, and can be replicated in my environment below with a simple `docker-compose restart` command.

I have also attached two of the "corrupted" (I guess?) `.explored` files, not sure if they're helpful.
[wootheim-explored-files.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6097334/wootheim-explored-files.zip)

## Environment
latest version of Valheim dedicated server, linux (containerized in docker), with only a handful of mods:
* BepInEx `5.4.8.0`
* [ValheimPlus](https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.4) `0.9.4`
* [CraftFromContainers](https://www.nexusmods.com/valheim/mods/40?tab=files) `1.1.2`run by this [docker image](https://github.com/mbround18/valheim-docker)
* ServerSideMap (`rc1-1.2.0` & `1.2.0`) (default config, no pin sharing)

I also attached my zipped config directory in case anything in there helps. 
[wootheim-config.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6097324/wootheim-config.zip)

I run the entire thing in docker, using [mbround18/valheim](https://github.com/mbround18/valheim-docker) docker image and the following `docker-compose.yml`

```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2467/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Wootheim"
      - WORLD="Wootheim2"
      - PASSWORD="coolkids!"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=0
    volumes:
      - /home/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/valheim/server:/home/steam/valheim
      - /home/valheim/backups:/home/steam/backups
```
